name: Tests

on: pull_request

env:
  FORCE_COLOR: 1
  DATABASE_URL: postgres://postgres:postgres@localhost/test

jobs:
  minitest:
    name: Minitest
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
      - name: Install Gems
        run: |
          gem install bundler
          bundle install
      - name: Run Minitest
        run: bundle exec rails test